### ISSUE TITLE
Error while trying to download SpeechComands dataset

### ISSUE THREAD

**Issue by teslyuk** [The-Learning-Machines/Audiomer-PyTorch#10]
Problem appears while running `python3 datamodules/SpeechCommands12.py`

> Traceback (most recent call last):
>   File "datamodules/SpeechCommands12.py", line 14, in <module>
>     import pytorch_lightning as pl
>   File "/Users/tesnik/Desktop/Audiomer-PyTorch/venv/lib/python3.7/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
>     from pytorch_lightning.callbacks import Callback  # noqa: E402
>   File "/Users/tesnik/Desktop/Audiomer-PyTorch/venv/lib/python3.7/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
>     from pytorch_lightning.callbacks.pruning import ModelPruning
>   File "/Users/tesnik/Desktop/Audiomer-PyTorch/venv/lib/python3.7/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
>     from pytorch_lightning.core.lightning import LightningModule
>   File "/Users/tesnik/Desktop/Audiomer-PyTorch/venv/lib/python3.7/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
>     from pytorch_lightning.core.lightning import LightningModule
>   File "/Users/tesnik/Desktop/Audiomer-PyTorch/venv/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 39, in <module>
>     from pytorch_lightning.trainer.connectors.logger_connector.fx_validator import _FxValidator
>   File "/Users/tesnik/Desktop/Audiomer-PyTorch/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/__init__.py", line 16, in <module>
>     from pytorch_lightning.trainer.trainer import Trainer
>   File "/Users/tesnik/Desktop/Audiomer-PyTorch/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 35, in <module>
>     from pytorch_lightning.loggers import LightningLoggerBase
>   File "/Users/tesnik/Desktop/Audiomer-PyTorch/venv/lib/python3.7/site-packages/pytorch_lightning/loggers/__init__.py", line 18, in <module>
>     from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
>   File "/Users/tesnik/Desktop/Audiomer-PyTorch/venv/lib/python3.7/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
>     from torch.utils.tensorboard import SummaryWriter
>   File "/Users/tesnik/Desktop/Audiomer-PyTorch/venv/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
>     LooseVersion = distutils.version.LooseVersion
> AttributeError: module 'setuptools._distutils' has no attribute 'version'

As you can see I'm using Python version == 3.7

**Comment by ojus1** [comment]
Hi,
I am pretty sure this because of mismatch in PyTorch, CUDA, and PyTorch Lightning versions.

IRCC The version of PyTorch Lightning that's used requires python>=3.8.5

Consider downgrading the version of PyTorch Lightning.

If it still doesn't work, maybe try with the versions in the readme and requirements.txt

**Comment by teslyuk** [comment]
Seems like this type of error is gone but there's still one

**Comment by teslyuk** [comment]
Hey, seems like previous problem is gone but there's one still pops up while trying to use this script:

> Traceback (most recent call last):
>   File "datamodules/SpeechCommands12.py", line 64, in <module>
>     from .pad import make_pad_function
> ModuleNotFoundError: No module named '__main__.pad'; '__main__' is not a package

**Comment by ojus1** [comment]
Hi, thanks for pointing it out.

In commit 046d959ecb34e10be7b353367f84a454b4449a25 I've added a script to download the dataset. You can use `python3 download_speechcommands.py` to download the dataset.

I'm closing the issue for now, feel free to open if there's any other issues.
