### ISSUE TITLE
A question about SubsetSC class

### ISSUE THREAD

**Issue by zyf001** [The-Learning-Machines/Audiomer-PyTorch#14]
I have a question about how to split the training set.   
As the code shows （“self._walker = [w for w in self._walker if w not in excludes]”）, it seems that the test and validation sets cannot be excluded from the training data.  
Maybe it should be written like this, "self._walker = [w for w in self._walker if ("./" + w) not in excludes]".
Thanks a lot.

**Comment by ojus1** [comment]
Thanks for pointing it out.
We'll publish the updated results soon.
