### ISSUE TITLE
ModuleNotFoundError: No module named 'Metrics'?

### ISSUE THREAD

**Issue by dragen1860** [The-Learning-Machines/Audiomer-PyTorch#7]
Dear author:
   I meet the following error when running evaluate.py:

```
(voice) loong@luntu:~/voice/Audiomer-PyTorch$ python evaluate.py --checkpoint_path ckpt/SC20/audiomerS_SC20_99.86.ckpt --model S --dataset SC20
Traceback (most recent call last):
  File "/home/loong/voice/Audiomer-PyTorch/evaluate.py", line 10, in <module>
    from Metrics import *
ModuleNotFoundError: No module named 'Metrics'
```

I can not find any implementation of `SpeechCommandsMetrics`. Does anythong go wrong?

**Comment by ojus1** [comment]
Hi!
Thanks for pointing it out. I forgot to push updated `evaluate.py` after refactoring code.
Commit 3100a17 has the updated script. Please test it now and reopen the issue if it doesn't work for you.
