### ISSUE TITLE
Import failing

### ISSUE THREAD

**Issue by annodomini80** [The-Learning-Machines/Audiomer-PyTorch#8]
https://github.com/The-Learning-Machines/Audiomer-PyTorch/blob/3100a174a52c9885bbf8b43410ce2c547300b581/datamodules/SpeechCommands12.py#L64

Try from pad import

**Comment by ojus1** [comment]
Hi, thanks for pointing it out.

In commit 046d959 I've added a script to download the dataset. You can use `python3 download_speechcommands.py` to download the dataset.
