### ISSUE TITLE
Allow CPU as well, or check if GPU exists

### ISSUE THREAD

**Issue by annodomini80** [The-Learning-Machines/Audiomer-PyTorch#9]
https://github.com/The-Learning-Machines/Audiomer-PyTorch/blob/3100a174a52c9885bbf8b43410ce2c547300b581/evaluate.py#L202

**Comment by annodomini80** [comment]
evaluate.py:    model.load_state_dict(torch.load(script_args.checkpoint_path, map_location=torch.device('cpu'))['state_dict'])

**Comment by ojus1** [comment]
Added an argument in the evaluation script. See Commit 7fe372a741cd5683f5670d93ba7b95ae53a9fd34 for details.
